"""Tests for D3 execution service (US-E2E-01.1 Task 10)."""

from __future__ import annotations

import uuid
from datetime import datetime

import pytest
import pytest_asyncio
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from app.models.capa_d3 import (
    CapaD3Execution,
    CapaD3AdviceGeneration,
    CapaD3AiAdvice,
    CapaD3AdviceAdoption,
    CapaD3ImpactReport,
)
from app.models.capa import CAPAEightD
from app.models.user import User
from app.services.capa_d3_containment_service import (
    record_execution,
    update_execution,
)

pytestmark = pytest.mark.requires_db


# ===== Fixtures =====


@pytest_asyncio.fixture
async def capa_d3_with_done_report(db, capa_d3_imported):
    """CAPA with done report but NO advice. Returns (capa, report, user)."""
    capa, run, user = capa_d3_imported
    # Report is already generated by capa_d3_imported fixture
    report = await db.scalar(
        select(CapaD3ImpactReport).where(
            CapaD3ImpactReport.run_id == run.run_id,
            CapaD3ImpactReport.is_current == True,
        )
    )
    return capa, report, user


@pytest_asyncio.fixture
async def capa_d3_with_adopted_advice(db, capa_d3_with_done_report, llm_mock):
    """CAPA with adopted advice. Returns (capa, report, advice, gen, user)."""
    capa, report, user = capa_d3_with_done_report

    # Mock LLM to return valid advice
    llm_mock.return_value = {
        "advice": [
            {
                "advice_type": "strict_inspection",
                "advice_text": "加强检验",
                "target_batch_refs": None,
                "provenance_sources_hint": ["iqc"],
            }
        ]
    }

    # Generate advice
    from app.services.capa_d3_containment_service import generate_advice

    await generate_advice(db, capa.report_id, report.report_id, user, None)

    # Get the current generation and advice
    gen = await db.scalar(
        select(CapaD3AdviceGeneration).where(
            CapaD3AdviceGeneration.report_id == report.report_id,
            CapaD3AdviceGeneration.is_current == True,
        )
    )
    advice = await db.scalar(
        select(CapaD3AiAdvice).where(CapaD3AiAdvice.generation_id == gen.generation_id)
    )

    # Adopt the advice
    adoption = CapaD3AdviceAdoption(
        adoption_id=uuid.uuid4(),
        advice_id=advice.advice_id,
        factory_id=advice.factory_id,
        decision="adopted",
        adopted_text="已采纳执行",
        advice_type=advice.advice_type,
        source_provenance=advice.source_provenance,
        decided_by=user.user_id,
        decided_at=datetime.utcnow(),
    )
    db.add(adoption)
    await db.flush()

    return capa, report, advice, gen, user


@pytest_asyncio.fixture
async def capa_d3_with_execution(db, capa_d3_with_done_report):
    """CAPA with execution (result_status='completed'). Returns (capa, ex_dict, user)."""
    capa, report, user = capa_d3_with_done_report

    ex = CapaD3Execution(
        execution_id=uuid.uuid4(),
        report_id=report.report_id,
        generation_id=None,
        advice_id=None,
        factory_id=report.factory_id,
        source="manual",
        measure_text="隔离库位 A",
        result_status="completed",
        evidence_refs=[],
        executed_by=user.user_id,
        executed_at=datetime.utcnow(),
    )
    db.add(ex)
    await db.flush()

    return capa, {
        "execution_id": str(ex.execution_id),
        "result_status": ex.result_status,
    }, user


@pytest_asyncio.fixture
async def two_capas_same_factory_with_done_report(db, capa_d3_imported, llm_mock):
    """Two CAPAs with done reports. Returns (capa_a, report_a, capa_b, user)."""
    capa_a, run_a, user = capa_d3_imported
    report_a = await db.scalar(
        select(CapaD3ImpactReport).where(
            CapaD3ImpactReport.run_id == run_a.run_id,
            CapaD3ImpactReport.is_current == True,
        )
    )

    # Create capa_b in same factory
    capa_b = CAPAEightD(
        report_id=uuid.uuid4(),
        document_no="CAPA-D3-002",
        title="D3 Test CAPA B",
        product_line_code="DC-DC-100",
        factory_id=capa_a.factory_id,
        status="D3_INTERIM",
        severity="serious",
    )
    db.add(capa_b)
    await db.flush()

    # Seed source data for capa_b
    from tests.capa.conftest import _seed_d3_source_data

    await _seed_d3_source_data(
        db,
        capa_b.factory_id,
        user.user_id,
        customer_code="CB",
        supplier_no="SUP-B",
        inspection_no="IQC-B",
        ic_code="IC-B",
    )

    # Import and generate report for capa_b
    llm_mock.return_value = {"risk_level": "medium", "risk_explanation": "ok"}
    from app.services.capa_d3_containment_service import (
        import_containment_data,
        generate_impact_report,
    )
    from app.models.capa_d3 import CapaD3ImportRun

    result = await import_containment_data(db, capa_b.report_id, user, {})
    run_b = await db.get(CapaD3ImportRun, uuid.UUID(result["run_id"]))

    return capa_a, report_a, capa_b, user


# ===== Service Tests =====


async def test_manual_execution_null_advice_generation(db, capa_d3_with_done_report):
    """Manual execution has NULL advice_id and generation_id."""
    capa, report, user = capa_d3_with_done_report
    ex = await record_execution(
        db,
        capa.report_id,
        report.report_id,
        user,
        {
            "source": "manual",
            "measure_text": "隔离库位 A",
            "result_status": "in_progress",
        },
    )
    assert ex["source"] == "manual"
    assert ex["advice_id"] is None
    assert ex["generation_id"] is None


async def test_adopted_execution_requires_advice_same_generation(
    db, capa_d3_with_adopted_advice
):
    """Adopted execution links to advice and generation."""
    capa, report, advice, gen, user = capa_d3_with_adopted_advice
    ex = await record_execution(
        db,
        capa.report_id,
        report.report_id,
        user,
        {
            "source": "adopted",
            "advice_id": advice.advice_id,
            "measure_text": "召回批次",
            "result_status": "in_progress",
        },
    )
    assert ex["generation_id"] == str(gen.generation_id)
    assert ex["advice_id"] == str(advice.advice_id)


async def test_check_manual_with_advice_id_rejected(db, capa_d3_with_done_report):
    """Manual execution with advice_id violates CHECK constraint."""
    capa, report, user = capa_d3_with_done_report
    # The service validates and raises ValueError before DB INSERT
    with pytest.raises(ValueError, match="manual execution should not have advice_id"):
        await record_execution(
            db,
            capa.report_id,
            report.report_id,
            user,
            {
                "source": "manual",
                "advice_id": str(uuid.uuid4()),
                "measure_text": "t",
                "result_status": "in_progress",
            },
        )


async def test_patch_demote_completed_to_failed(db, capa_d3_with_execution):
    """PATCH can change result_status from completed to failed."""
    capa, ex, user = capa_d3_with_execution
    await update_execution(
        db,
        capa.report_id,
        uuid.UUID(ex["execution_id"]),
        user,
        {"result_status": "failed"},
    )
    # Verify the change was persisted
    ex_db = await db.get(CapaD3Execution, uuid.UUID(ex["execution_id"]))
    assert ex_db.result_status == "failed"


async def test_patch_writes_full_field_audit(
    db, capa_d3_with_execution, audit_reader
):
    """PATCH writes old/new values to audit log."""
    capa, ex, user = capa_d3_with_execution
    await update_execution(
        db,
        capa.report_id,
        uuid.UUID(ex["execution_id"]),
        user,
        {
            "result_status": "failed",
            "measure_text": "新文本",
            "evidence_refs": [
                {
                    "name": "e2",
                    "url": "https://x.com/a",
                    "uploaded_at": "2026-07-10T00:00:00Z",
                }
            ],
        },
    )
    upd = await audit_reader(capa.report_id, "D3_EXECUTION_UPDATED")
    assert upd["old_result_status"] == "completed"
    assert upd["new_result_status"] == "failed"
    assert upd.get("measure_text_changed") is True


async def test_patch_empty_evidence_refs_clears(db, capa_d3_with_execution):
    """PATCH evidence_refs=[] clears evidence."""
    capa, ex, user = capa_d3_with_execution

    # First add some evidence
    await update_execution(
        db,
        capa.report_id,
        uuid.UUID(ex["execution_id"]),
        user,
        {
            "evidence_refs": [
                {
                    "name": "e1",
                    "url": "https://x.com/b",
                    "uploaded_at": "2026-07-10T00:00:00Z",
                }
            ]
        },
    )

    # Now clear it
    await update_execution(
        db,
        capa.report_id,
        uuid.UUID(ex["execution_id"]),
        user,
        {"evidence_refs": []},
    )
    ex_db = await db.get(CapaD3Execution, uuid.UUID(ex["execution_id"]))
    assert ex_db.evidence_refs == []


async def test_evidence_refs_https_allowed(db, capa_d3_with_done_report):
    """Allow https:// URLs in evidence_refs."""
    capa, report, user = capa_d3_with_done_report
    ex = await record_execution(
        db,
        capa.report_id,
        report.report_id,
        user,
        {
            "source": "manual",
            "measure_text": "t",
            "result_status": "in_progress",
            "evidence_refs": [
                {
                    "name": "e",
                    "url": "https://x.com/a",
                    "uploaded_at": "2026-07-10T00:00:00Z",
                }
            ],
        },
    )
    assert ex["execution_id"]


async def test_evidence_refs_javascript_rejected(db, capa_d3_with_done_report):
    """Reject javascript: URLs in evidence_refs."""
    capa, report, user = capa_d3_with_done_report
    with pytest.raises(ValueError, match="非法 url scheme"):
        await record_execution(
            db,
            capa.report_id,
            report.report_id,
            user,
            {
                "source": "manual",
                "measure_text": "t",
                "result_status": "in_progress",
                "evidence_refs": [
                    {
                        "name": "e",
                        "url": "javascript:alert(1)",
                        "uploaded_at": "2026-07-10T00:00:00Z",
                    }
                ],
            },
        )


async def test_evidence_refs_file_data_rejected(db, capa_d3_with_done_report):
    """Reject file: and data: URLs in evidence_refs."""
    capa, report, user = capa_d3_with_done_report
    for bad in ["file:///etc/passwd", "data:text/html,x"]:
        with pytest.raises(ValueError, match="非法 url scheme"):
            await record_execution(
                db,
                capa.report_id,
                report.report_id,
                user,
                {
                    "source": "manual",
                    "measure_text": "t",
                    "result_status": "in_progress",
                    "evidence_refs": [
                        {
                            "name": "e",
                            "url": bad,
                            "uploaded_at": "2026-07-10T00:00:00Z",
                        }
                    ],
                },
            )


async def test_evidence_refs_protocol_relative_rejected(db, capa_d3_with_done_report):
    """Reject // URLs in evidence_refs."""
    capa, report, user = capa_d3_with_done_report
    with pytest.raises(ValueError, match="非法 url scheme"):
        await record_execution(
            db,
            capa.report_id,
            report.report_id,
            user,
            {
                "source": "manual",
                "measure_text": "t",
                "result_status": "in_progress",
                "evidence_refs": [
                    {
                        "name": "e",
                        "url": "//evil.example/path",
                        "uploaded_at": "2026-07-10T00:00:00Z",
                    }
                ],
            },
        )


async def test_execution_cross_capa_same_factory_404(
    db, two_capas_same_factory_with_done_report
):
    """Cross-CAPA report_id returns 404."""
    capa_a, report_a, capa_b, user = two_capas_same_factory_with_done_report
    with pytest.raises(LookupError, match="报告不属于该 CAPA"):
        await record_execution(
            db,
            capa_b.report_id,
            report_a.report_id,
            user,
            {
                "source": "manual",
                "measure_text": "t",
                "result_status": "in_progress",
            },
        )


async def test_execution_cross_factory_404(db, capa_d3_with_execution, default_factory):
    """Cross-factory execution returns 404."""
    capa, ex, user = capa_d3_with_execution

    # Create a different user in a different factory
    from app.models.factory import Factory
    from app.models.role import RoleDefinition

    other_factory = Factory(
        id=uuid.uuid4(),
        code="OTHER-FAC",
        name="Other Factory",
        is_active=True,
    )
    db.add(other_factory)
    await db.flush()

    role = RoleDefinition(
        id=uuid.uuid4(),
        role_key="test_role_other",
        name_zh="Other Role",
        name_en="Other Role",
        description="Test",
        is_system=False,
        is_editable=True,
        is_active=True,
    )
    db.add(role)
    await db.flush()

    other_user = User(
        user_id=uuid.uuid4(),
        username="other_user",
        display_name="Other User",
        email="other@example.com",
        password_hash="test_hash",
        role_id=role.id,
        legacy_role="viewer",
        is_active=True,
        factory_id=other_factory.id,
    )
    db.add(other_user)
    await db.flush()

    # The cross-factory check is based on capa_id vs execution.factory_id
    # We need to create a different CAPA in other_factory to test this
    other_capa = CAPAEightD(
        report_id=uuid.uuid4(),
        document_no="CAPA-OTHER",
        title="Other CAPA",
        product_line_code="DC-DC-100",
        factory_id=other_factory.id,
        status="D3_INTERIM",
        severity="serious",
    )
    db.add(other_capa)
    await db.flush()

    # Try to update execution with wrong capa_id (different factory)
    with pytest.raises(LookupError, match="执行记录不属于该 CAPA"):
        await update_execution(
            db,
            other_capa.report_id,
            uuid.UUID(ex["execution_id"]),
            other_user,
            {"result_status": "failed"},
        )