"""Correct D3 execution composite foreign keys (US-E2E-01.1 follow-up)

Revision ID: 20260713_d3_execution_fk_correct
Revises: 20260712_shipment_factory_id
Create Date: 2026-07-13

Some deployed databases carry the autogenerated single-column FKs on
`capa_d3_execution.generation_id` and `advice_id` (named
`fk_d3_exec_gen_factory` / `fk_d3_exec_advice_factory`) instead of the
required 3-column composite FKs. This migration drops the old FKs and
adds/verifies the correct composite ones, plus the parent UQ they need.

Idempotent: all DDL uses IF EXISTS / IF NOT EXISTS checks.
"""
from alembic import op
import sqlalchemy as sa


revision = "20260713_d3_execution_fk_correct"
down_revision = "20260712_shipment_factory_id"
branch_labels = None
depends_on = None


def _exec_if_not_exists(table: str, constraint: str, ddl: str) -> None:
    """Run DDL only if the constraint does not already exist.

    Uses plain string interpolation because PostgreSQL DO blocks do not
    accept bound parameters.
    """
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints
                    WHERE constraint_name = '{constraint}'
                      AND table_name = '{table}'
                ) THEN
                    {ddl};
                END IF;
            END $$;
            """
        )
    )


def upgrade() -> None:
    # Drop old single-column FKs if they exist.
    op.execute(
        sa.text(
            "ALTER TABLE capa_d3_execution DROP CONSTRAINT IF EXISTS fk_d3_exec_gen_factory"
        )
    )
    op.execute(
        sa.text(
            "ALTER TABLE capa_d3_execution DROP CONSTRAINT IF EXISTS fk_d3_exec_advice_factory"
        )
    )

    # Ensure the parent unique constraint for the composite FK target exists.
    _exec_if_not_exists(
        "capa_d3_advice_generation",
        "uq_d3_generation_report",
        "ALTER TABLE capa_d3_advice_generation "
        "ADD CONSTRAINT uq_d3_generation_report "
        "UNIQUE (generation_id, report_id, factory_id)",
    )

    # Add correct 3-column composite FKs if missing.
    _exec_if_not_exists(
        "capa_d3_execution",
        "fk_d3_exec_gen_report_factory",
        "ALTER TABLE capa_d3_execution "
        "ADD CONSTRAINT fk_d3_exec_gen_report_factory "
        "FOREIGN KEY (generation_id, report_id, factory_id) "
        "REFERENCES capa_d3_advice_generation(generation_id, report_id, factory_id) "
        "ON DELETE RESTRICT",
    )
    _exec_if_not_exists(
        "capa_d3_execution",
        "fk_d3_exec_advice_gen_factory",
        "ALTER TABLE capa_d3_execution "
        "ADD CONSTRAINT fk_d3_exec_advice_gen_factory "
        "FOREIGN KEY (advice_id, generation_id, factory_id) "
        "REFERENCES capa_d3_ai_advice(advice_id, generation_id, factory_id) "
        "ON DELETE RESTRICT",
    )


def downgrade() -> None:
    # Drop correct composite FKs.
    op.execute(
        sa.text(
            "ALTER TABLE capa_d3_execution DROP CONSTRAINT IF EXISTS fk_d3_exec_advice_gen_factory"
        )
    )
    op.execute(
        sa.text(
            "ALTER TABLE capa_d3_execution DROP CONSTRAINT IF EXISTS fk_d3_exec_gen_report_factory"
        )
    )
    op.execute(
        sa.text(
            "ALTER TABLE capa_d3_advice_generation DROP CONSTRAINT IF EXISTS uq_d3_generation_report"
        )
    )

    # Restore old single-column FKs (the pre-corrective state).
    _exec_if_not_exists(
        "capa_d3_execution",
        "fk_d3_exec_gen_factory",
        "ALTER TABLE capa_d3_execution "
        "ADD CONSTRAINT fk_d3_exec_gen_factory "
        "FOREIGN KEY (generation_id) "
        "REFERENCES capa_d3_advice_generation(generation_id) "
        "ON DELETE RESTRICT",
    )
    _exec_if_not_exists(
        "capa_d3_execution",
        "fk_d3_exec_advice_factory",
        "ALTER TABLE capa_d3_execution "
        "ADD CONSTRAINT fk_d3_exec_advice_factory "
        "FOREIGN KEY (advice_id) "
        "REFERENCES capa_d3_ai_advice(advice_id) "
        "ON DELETE RESTRICT",
    )
