"""create_fmea_capa_audit_tables

Revision ID: e3a252cd331f
Revises: 275a49e8b270
Create Date: 2026-05-19 16:48:32.512432
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e3a252cd331f'
down_revision: Union[str, None] = '275a49e8b270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operated_by', sa.UUID(), nullable=True),
    sa.Column('operated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('fmea_documents',
    sa.Column('fmea_id', sa.UUID(), nullable=False),
    sa.Column('document_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('fmea_type', sa.String(length=20), nullable=False),
    sa.Column('product_line_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('graph_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('fmea_id'),
    sa.UniqueConstraint('document_no')
    )
    op.create_table('capa_eightd',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('document_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('product_line_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('d1_team', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('d2_description', sa.Text(), nullable=True),
    sa.Column('d3_interim', sa.Text(), nullable=True),
    sa.Column('d4_root_cause', sa.Text(), nullable=True),
    sa.Column('d5_correction', sa.Text(), nullable=True),
    sa.Column('d6_verification', sa.Text(), nullable=True),
    sa.Column('d7_prevention', sa.Text(), nullable=True),
    sa.Column('d8_closure', sa.Text(), nullable=True),
    sa.Column('fmea_ref_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['fmea_ref_id'], ['fmea_documents.fmea_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('document_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capa_eightd')
    op.drop_table('fmea_documents')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
